name: cardDetailScrap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  cardDetailScrap:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 원격 브랜치의 전체 히스토리를 가져옵니다.

    - name: 파이썬 설정
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install lxml
        pip install pandas
        pip install html5lib
        pip install selenium
        pip install webdriver_manager
       
    - name: 스크립트 실행
      run: |
        python scrapDetail.py

    - name: 변경사항 검사
      id: changes
      run: |
        git status
        if git diff-index --quiet HEAD --; then
            echo "::set-output name=changes_exist::false"
        else
            echo "::set-output name=changes_exist::true"
        
    - name: 원격 브랜치 최신 상태 통합
      run: |
        git pull origin main --no-edit  # 원격 브랜치를 풀하여 최신 상태로 유지
    
    - name: 커밋 설정
      if: steps.changes.outputs.changes_exist == 'true'
      run: |
        git config --global user.email "dlwogur0712@gmail.com"
        git config --global user.name "jaehyuk-lee-0712"
        git add scrapList/scrapCardDetail_*.json
        git commit -m "신용카드 데이터 수집"
        
    - name: 푸시
      if: steps.changes.outputs.changes_exist == 'true'
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
