name: cardScrap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  cardScrap:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: 파이썬 설정
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
        
    - name: 의존성 설치
      run: |
        python -m pip install --upgrade pip
    - name: 라이브러리 설치
      run: |
        pip install requests
        pip install beautifulsoup4
        pip install lxml
        pip install pandas
        pip install html5lib
        pip install selenium
        pip install webdriver_manager
       
    - name: 스크립트 실행
      run: |
        python scrap.py
    - name: 커밋 설정
      run: |
        git config --global user.email "dlwogur0712@gmail.com"
        git config --global user.name "jaehyuk-lee-0712"
        git add scrapList/cardHana_*.json
        git add scrapList/cardHyundai_*.json
        git add scrapList/cardIBK_*.json
        git add scrapList/cardKB_*.json
        git add scrapList/cardLotte_*.json
        git add scrapList/cardNH_*.json
        git add scrapList/cardSamsung_*.json
        git add scrapList/cardSinhan_*.json
        git add scrapList/cardWoori_*.json
        git commit -m "신용카드 데이터 수집"
    - name: 푸시
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
